### ISSUE TITLE
connectDMTP function not throwing error

### ISSUE THREAD

**Issue by shynnhuy** [DMTP-Protocol/DMTP-SDK-REACT#4]
async function connectDMTP is not throwing error when user reject the sign message

https://github.com/DMTP-Protocol/DMTP-SDK-REACT/blob/5ef9fa89a5e81a72d6b9546a554df8c59ad3ac8e/src/hooks/DMTPHook.ts#L8-L118

**Comment by Aqrare** [comment]
Could you set isDev to DMTPProvider like this ?

<DMTPProvider
        isDev
        APIKey="API_KEY"
        dappAddress="ADDRESS"
      >

> async function connectDMTP is not throwing error when user reject the sign message
> 
> https://github.com/DMTP-Protocol/DMTP-SDK-REACT/blob/5ef9fa89a5e81a72d6b9546a554df8c59ad3ac8e/src/hooks/DMTPHook.ts#L8-L118

Could you add isDev to DMTPProvider like this ??

<DMTPProvider
        isDev
        APIKey="API_KEY"
        dappAddress="ADDRESS"
      >

**Comment by shynnhuy** [comment]
yes. i'm already set isDev in DMTPProvider but when i'm using `await connectDMTP()` in try catch block and user is reject the sign message then the function is still running

```
try {
   await connectDMTP();
   await login(); // Still executed this function
} catch (error: any) {
   console.log(error); // Nothing happen here
}
```
